print("Welcome to the tip calculator.")
bill=input("What are the total bill ?  $")
tip=input("What percentage tip would you like to give? 10, 12 or 15?")
bill_splitter=input("How many people to split the bill? ")
tip_as_percentage= (float(tip)/100)*float(bill) 
total_tip_amount=float(tip_as_percentage)+float(bill)
tip_amount=float(total_tip_amount)/float(bill_splitter)
# per_one_bill=float(round(tip_amount,2))
per_one_bill="{:.2f}".format(tip_amount)
print(f"Each person should pay: ${per_one_bill}")